data <- read.csv("repdata-data-StormData.csv.bz2")
library(dplyr)
str(data)
names(data)
length(data$STATE__) == length(data$STATE)
table(data$EVTYPE)
table(data$FATALITIES)
hist(data$FATALITIES)
table(data$INJURIES)
harm <- filter(data, FATALITIES > 0 |
                 data$INJURIES > 0)
table(harm$FATALITIES, harm$INJURIES)
events <- table(harm$EVTYPE)
arrange(harm, desc(FATALITIES), desc(INJURIES))
